Update act-rules-format.bs
w3c/wcag-act pull request #556
Opened 2023-12-12 19:59 UTC by kengdoj

2023-12-13 13:21 UTC, daniel-montalvo requested changes
I'd suggest to use the spec name "ACT Rules Format" Not feeling strongly though. throughout. I also caught a typo.

2023-12-13 13:21 UTC, daniel-montalvo commented on act-rules-format/act-rules-format.bs
> +Rules Format Version {#rules-format-version}
```suggestion
ACT Rules Format Version {#act-rules-format-version}
```

To be consistent with spec name

2023-12-13 13:21 UTC, daniel-montalvo commented on act-rules-format/act-rules-format.bs
> +ACT Rules <em class="rfc2119">must</em> indicate the rule's compatibility to a version of the Rules Format as each version has different requirements.
```suggestion
ACT Rules <em class="rfc2119">must</em> indicate the rule's compatibility to a version of the ACT Rules Format as each version has different requirements. 
```

Same as above.

2023-12-13 13:21 UTC, daniel-montalvo commented on act-rules-format/act-rules-format.bs
> +  <li><strong>4.12 Rules Format Version</strong> New requirement to identify rules format version compatiblity</li>
```suggestion
  <li><strong>4.12 ACT Rules Format Version</strong> New requirement to identify ACT Rules Format version compatibility</li>
```

2023-12-19 14:12 UTC, kengdoj commented on act-rules-format/act-rules-format.bs
> +* [Rules Format Version](#rules-format-version)
```suggestion
* [ACT Rules Format Version](#act-rules-format-version)
```

2023-12-19 14:20 UTC, WilcoFiers commented on act-rules-format/act-rules-format.bs
> +ACT Rules <em class="rfc2119">must</em> indicate the rule's compatibility to a version of the ACT Rules Format as each version has different requirements.
> An ACT Rule is written for a specific version of the ACT Rules Format. Each rule MUST indicate which version of the rules format it is written for.

2023-12-19 15:16 UTC, kengdoj commented on act-rules-format/act-rules-format.bs
> +ACT Rules <em class="rfc2119">must</em> indicate the rule's compatibility to a version of the ACT Rules Format as each version has different requirements.
```suggestion
An ACT Rule is written for a specific version of the ACT Rules Format. Each ACT Rule <em class="rfc2119">MUST</em> indicate the version of the ACT Rules Format for which it is written. 
```

2023-12-19 15:59 UTC, daniel-montalvo approved these changes

2023-12-21 18:10 UTC, kengdoj commented on act-rules-format/act-rules-format.bs
> +An ACT Rule is written for a specific version of the ACT Rules Format. Each ACT Rule <em class="rfc2119">MUST</em> indicate the version of the ACT Rules Format for which it is written.
```suggestion
An ACT Rule is written for a specific version of the ACT Rules Format. Each ACT Rule <em class="rfc2119">must</em> indicate the version of the ACT Rules Format for which it is written. 
```

2024-01-11 14:14 UTC, WilcoFiers approved these changes

2024-01-11 14:14 UTC, tbostic32 approved these changes

2024-01-11 14:17 UTC, WilcoFiers commented on act-rules-format/act-rules-format.bs
>    <li><strong>4.14. Implementations<strong> New section has been added, including a method for determining consistency with ACT Rules</li>
```suggestion
  <li><strong>4.15. Implementations<strong> New section has been added, including a method for determining consistency with ACT Rules</li>
```

2024-01-11 14:17 UTC, tombrunet approved these changes

2024-01-11 15:10 UTC, merged